 import lottery from "../src/assets/img/lottery.gif"
import logo from '../src/assets/img/n1.svg';
var data = [
  {
    "category": "Column 1",
    "questions": [
      {
        "number": 1,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 2,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "number": 3,
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 4,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 5,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 6,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "number": 7,
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 8,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      { 
        "number": 9,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 10,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      }
    ]
  },
  {
    "category": "Column 2",
    "questions": [
      {
        "number": 11,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 12,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 13,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 14,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 15,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 16,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 17,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 18,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 19,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 20,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      }
    ]
  },
  {
    "category": "Column 3",
    "questions": [
      {
        "number": 1,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 2,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "number": 3,
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 4,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 5,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 6,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "number": 7,
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 8,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      { 
        "number": 9,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 10,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      }
    ]
  },
  {
    "category": "Column 4",
    "questions": [
      {
        "number": 11,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 12,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 13,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 14,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 15,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 16,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 17,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 18,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 19,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 20,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      }
    ]
  },
  {
    "category": "Column 5",
    "questions": [
      {
        "number": 1,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 2,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "number": 3,
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 4,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 5,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 6,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "number": 7,
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 8,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      { 
        "number": 9,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 10,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      }
    ]
  },
  {
    "category": "Column 6",
    "questions": [
      {
        "number": 11,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 12,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 13,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 14,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 15,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 16,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 17,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 18,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 19,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 20,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      }
    ]
  },
  {
    "category": "Column 7",
    "questions": [
      {
        "number": 1,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 2,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "number": 3,
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 4,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 5,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 6,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "number": 7,
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 8,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      { 
        "number": 9,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 10,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      }
    ]
  },
  {
    "category": "Column 8",
    "questions": [
      {
        "number": 11,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 12,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 13,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 14,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 15,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 16,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 17,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 18,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 19,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 20,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      }
    ]
  },
  {
    "category": "Column 9",
    "questions": [
      {
        "number": 1,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 2,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "number": 3,
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 4,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 5,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 6,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "number": 7,
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 8,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      { 
        "number": 9,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 10,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      }
    ]
  },
  {
    "category": "Column 10",
    "questions": [
      {
        "number": 11,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 12,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 13,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 14,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 15,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 16,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 17,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 18,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 19,
        "type": "B",
        "icon":logo,
        "color": "#7eaa38",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      },
      {
        "number": 20,
        "type": "A",
        "icon": lottery,
        "color": "#5a3a97",
        "question": "Hurray !! You have won 10 bonusly from Netcentric",
      }
    ]
  },

];

export default data;